
uds_echo_server: uds_echo_server.c
	gcc -o uds_echo_server uds_echo_server.c

uds_echo_client: uds_echo_client.c
	gcc -o uds_echo_client uds_echo_client.c

all: uds_echo_server uds_echo_client
clean: 
	rm -f uds_echo_server uds_echo_client
